# Generated by Django 6.0 on 2025-12-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(default=0, max_length=14, unique=True),
            preserve_default=False,
        ),
    ]
