# Generated by Django 6.0 on 2025-12-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nome_mae',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
