# Generated by Django 6.0 on 2025-12-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('coren', models.CharField(max_length=20)),
                ('setor', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
