# Generated by Django 6.0 on 2025-12-14 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enfermeiros', '0001_initial'),
        ('pacientes', '0002_paciente_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chegada', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando Triagem'), ('EM_TRIAGEM', 'Em Triagem'), ('FINALIZADO', 'Triagem Finalizada')], default='AGUARDANDO', max_length=20)),
                ('enfermeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enfermeiros.enfermeiro')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
