# Generated by Django 6.0 on 2025-12-14 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enfermeiros', '0001_initial'),
        ('pacientes', '0002_paciente_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressao_arterial', models.CharField(max_length=10)),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('frequencia_cardiaca', models.IntegerField()),
                ('classificacao', models.CharField(choices=[('VERMELHO', '🔴 Vermelho – Emergência'), ('LARANJA', '🟠 Laranja – Muito urgente'), ('AMARELO', '🟡 Amarelo – Urgente'), ('VERDE', '🟢 Verde – Pouco urgente'), ('AZUL', '🔵 Azul – Não urgente')], max_length=10)),
                ('observacoes', models.TextField(blank=True)),
                ('enviada_medico', models.BooleanField(default=False)),
                ('data_triagem', models.DateTimeField(auto_now_add=True)),
                ('enfermeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enfermeiros.enfermeiro')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
