# Generated by Django 6.0 on 2025-12-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triagem',
            old_name='data_triagem',
            new_name='criado_em',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='observacoes',
        ),
        migrations.AlterField(
            model_name='triagem',
            name='classificacao',
            field=models.CharField(choices=[('VERMELHO', 'Emergência'), ('LARANJA', 'Muito urgente'), ('AMARELO', 'Urgente'), ('VERDE', 'Pouco urgente'), ('AZUL', 'Não urgente')], default='VERDE', max_length=10),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='frequencia_cardiaca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='pressao_arterial',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='temperatura',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
