# Generated by Django 6.0 on 2025-12-14 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0002_rename_data_triagem_triagem_criado_em_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triagem',
            old_name='criado_em',
            new_name='criada_em',
        ),
        migrations.RenameField(
            model_name='triagem',
            old_name='enviada_medico',
            new_name='finalizada',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='classificacao',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='frequencia_cardiaca',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='pressao_arterial',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='temperatura',
        ),
    ]
